version: "3"
    
services:
  client:
    build: .
    restart: always
    network_mode: "host"
    environment:
      - PLAYER_COUNT=20
      - SERVER_IP=localhost
      - SERVER_PORT=25565
    volumes:
      - ./scripts:/app/scripts
